/* Autogenerated File */
/* eslint-disable comma-dangle */
/* eslint-disable max-len */
import { Question } from "../lib";

export const mockQuestions: Question[] = [
  {
    "questionID": "b4cD9D65ecAa9E37fFe4079146Ea9eDb4Ab31077A1dFDF8E5D2f8c63",
    "question": "Will Leonard Cummings exhort tonic?",
    "description": "Culpo sapiente temperantia. Usitas ea iusto acies. Asporto vulnus exercitationem summopere.",
    "categories": [
      "pop culture",
      "business"
    ],
    "imageUrl": "https://picsum.photos/seed/kwBvTM/1100/509",
    "dueDate": 1708056297760,
    "outcome": "Yes"
  },
  {
    "questionID": "3ae48ffb2ECaCeB7b3b59b2BeB2D25534488f2bfBdc574942b3b97a7",
    "question": "Will Colt Stanton bequeath disruption?",
    "description": "Libero ascit cura curia tantillus thermae laborum. Talus cura similique crudelis bellicus spero aliquid considero suppellex. Vicissitudo adversus necessitatibus certe usus ustulo defleo excepturi comburo.",
    "categories": [
      "politics"
    ],
    "imageUrl": "https://picsum.photos/seed/icnmKL/1100/509",
    "dueDate": 1708415667200,
    "outcome": "No"
  },
  {
    "questionID": "F736B96a82D13Ef2f749a9aFB6565D6d07B640f12C2C0fbA1DCcb221",
    "question": "Will Lafayette Weissnat-Kuhn trampoline setting?",
    "description": "Una decor correptius theatrum valens corrupti. Voluptatum fugiat audio aestus. Curriculum tripudio alienus benigne.",
    "categories": [
      "business"
    ],
    "imageUrl": "https://picsum.photos/seed/kzKQeJ/1100/509",
    "dueDate": 1699353807011,
    "outcome": "Yes"
  },
  {
    "questionID": "deE31C3E7B81fF6d1001f1a4A08fbFdE8EE42Eb8C661F0F465A2C30f",
    "question": "Will Morgan Dooley josh crepe?",
    "description": "Veritatis totam ea dolorum canis statua cumque. Somnus nesciunt comburo. Sopor denuo valeo.",
    "categories": [
      "pop culture",
      "politics"
    ],
    "imageUrl": "https://picsum.photos/seed/g4LDsz/1100/509",
    "dueDate": 1724213280434,
    "outcome": "No"
  },
  {
    "questionID": "DdcBa9deDE7ce57C9afa768EC9e6Db0cdb3aaC35fBA2bcb5CD4bcF3b",
    "question": "Will Modesta Hand request army?",
    "description": "Tutamen tergum conitor accendo earum perferendis tamdiu suadeo condico. Contigo numquam trepide qui eaque xiphias architecto atqui arcesso cupiditate. Caelum sint vespillo deludo facere aiunt dolores adulescens tenax rerum.",
    "categories": [
      "pop culture"
    ],
    "imageUrl": "https://picsum.photos/seed/yuk0YR/1100/509",
    "dueDate": 1706337338061,
    "outcome": "No"
  },
  {
    "questionID": "1dDa37d4FE48D48a7d7fB0b7D3acb3aCeeE7Fadf2aBcDAB7BE2F1b5E",
    "question": "Will Francis Franey martyr thrift?",
    "description": "Cubicularis porro commodo despecto tracto approbo depereo. Utrimque confero crapula amo avaritia dignissimos titulus cresco. Subito infit voluptatibus valens defleo confugo sustineo totus.",
    "categories": [
      "business"
    ],
    "imageUrl": "https://picsum.photos/seed/T2xMRl/1100/509",
    "dueDate": 1728186280528,
    "outcome": "Undefined"
  },
  {
    "questionID": "b050F19B1490b807e3ecBEA2bdE2E2032DD8feabce5DeFfE0ed11cfC",
    "question": "Will Eriberto Kreiger quiver serval?",
    "description": "Acsi est stillicidium decipio coadunatio damno veritatis non absconditus thalassinus. Fuga amet ut cavus auctus. In venio virga blanditiis veritatis agnosco.",
    "categories": [
      "politics",
      "sports"
    ],
    "imageUrl": "https://picsum.photos/seed/5F5ly4/1100/509",
    "dueDate": 1711937257942,
    "outcome": "Undefined"
  },
  {
    "questionID": "D3b8EB27A525D45cFddFdCfAcEFaBd761A1e2Ddb8f89E80acd987bf3",
    "question": "Will Addison Weissnat downsize gliding?",
    "description": "Veritatis uxor tepesco sol. Cattus valetudo speciosus creptio sto bellicus sperno absum. Vacuus cito chirographum conicio succurro denego.",
    "categories": [
      "sports",
      "business"
    ],
    "imageUrl": "https://picsum.photos/seed/RBeMPH/1100/509",
    "dueDate": 1714872173763,
    "outcome": "No"
  }
];
